# Generated by Django 5.2 on 2025-04-17 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='owner',
        ),
    ]
